### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by therisy** [Noirrs/getStructure#2]
- use body decorator instead of checking body from @req
- you can design the file as modules and core
- can change it to utils instead of functions name (src/core/kebab-case)
- If there will be only one type file, you can change it to types.d.ts (src/types.d.ts)

**Comment by noirrs** [comment]
Thanks for your feedback & issue!

Fixed at https://github.com/Noirrs/getStructure/commit/5608a6321e0b049b7c36afb29ad60de2c4e8ca3d
